// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlsPKLhG-Ot34UUGswx8Vwhd7IPhwiF6U',
    appId: '1:583861131077:web:5e1d68820ed5e84beb102c',
    messagingSenderId: '583861131077',
    projectId: 'marketplace-app-d3483',
    authDomain: 'marketplace-app-d3483.firebaseapp.com',
    storageBucket: 'marketplace-app-d3483.firebasestorage.app',
    measurementId: 'G-FHP7370CRJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0OvNjbITE0G7xdUzlcwg0J7URhB8MhoI',
    appId: '1:583861131077:android:98ad6a6945000ba9eb102c',
    messagingSenderId: '583861131077',
    projectId: 'marketplace-app-d3483',
    storageBucket: 'marketplace-app-d3483.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGsJda1kETGu58yXqlJGXTjgK08Wefjw0',
    appId: '1:583861131077:ios:acde8966e1a5428beb102c',
    messagingSenderId: '583861131077',
    projectId: 'marketplace-app-d3483',
    storageBucket: 'marketplace-app-d3483.firebasestorage.app',
    iosBundleId: 'com.example.marketplaceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGsJda1kETGu58yXqlJGXTjgK08Wefjw0',
    appId: '1:583861131077:ios:acde8966e1a5428beb102c',
    messagingSenderId: '583861131077',
    projectId: 'marketplace-app-d3483',
    storageBucket: 'marketplace-app-d3483.firebasestorage.app',
    iosBundleId: 'com.example.marketplaceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlsPKLhG-Ot34UUGswx8Vwhd7IPhwiF6U',
    appId: '1:583861131077:web:f4c73b28c623a0fceb102c',
    messagingSenderId: '583861131077',
    projectId: 'marketplace-app-d3483',
    authDomain: 'marketplace-app-d3483.firebaseapp.com',
    storageBucket: 'marketplace-app-d3483.firebasestorage.app',
    measurementId: 'G-LNBLZML6R3',
  );
}
